resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: maven_coverage

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    buildDockerArtifact: true
    coverageClassFilter: +:no.difi.*,-:no.difi.meldingsutveksling.serviceregistry.svarut*.*
    

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
