resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: maven_coverage

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    buildDockerArtifact: true
    coverageClassFilesDirectories: common/target/classes,domain/target/classes,kontakt-reservasjonsregister-client/target/classes,ks-fiks/target/classes,serviceregistry-server/target/classes
    coverageSourceDirectories: common/src/main,domain/src/main,kontakt-reservasjonsregister-client/src/main,ks-fiks/src/main,serviceregistry-server/src/main
    coverageClassFilter: +:no.difi.*,-:no.difi.meldingsutveksling.serviceregistry.svarut*.*

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
